#define DECLARE_INSTRUCTION_6502(Name) static instruction_6502 Name
#define DEFINE_INSTRUCTION_6502(Name) static void Name(nes_console* Console)

typedef void instruction_6502(nes_console*);

typedef enum
{
	ADDRESSING_ABSOLUTE,
	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_ABSOLUTE_Y,
	ADDRESSING_ZEROPAGE,
	ADDRESSING_ZEROPAGE_X,
	ADDRESSING_ZEROPAGE_Y,
	ADDRESSING_INDIRECT,
	ADDRESSING_INDIRECT_X,
	ADDRESSING_INDIRECT_Y,

	ADDRESSING_NONE,
	ADDRESSING_IMPLIED,
	ADDRESSING_RELATIVE,
	ADDRESSING_IMMEDIATE,
	ADDRESSING_ACCUMULATOR,
} addressing_mode;

DECLARE_INSTRUCTION_6502(ADC);
DECLARE_INSTRUCTION_6502(AND);
DECLARE_INSTRUCTION_6502(ASL);
DECLARE_INSTRUCTION_6502(BCC);
DECLARE_INSTRUCTION_6502(BCS);
DECLARE_INSTRUCTION_6502(BEQ);
DECLARE_INSTRUCTION_6502(BIT);
DECLARE_INSTRUCTION_6502(BMI);
DECLARE_INSTRUCTION_6502(BNE);
DECLARE_INSTRUCTION_6502(BPL);
DECLARE_INSTRUCTION_6502(BRK);
DECLARE_INSTRUCTION_6502(BVC);
DECLARE_INSTRUCTION_6502(BVS);
DECLARE_INSTRUCTION_6502(CLC);
DECLARE_INSTRUCTION_6502(CLD);
DECLARE_INSTRUCTION_6502(CLI);
DECLARE_INSTRUCTION_6502(CLV);
DECLARE_INSTRUCTION_6502(CMP);
DECLARE_INSTRUCTION_6502(CPX);
DECLARE_INSTRUCTION_6502(CPY);
DECLARE_INSTRUCTION_6502(DEC);
DECLARE_INSTRUCTION_6502(DEX);
DECLARE_INSTRUCTION_6502(DEY);
DECLARE_INSTRUCTION_6502(EOR);
DECLARE_INSTRUCTION_6502(INC);
DECLARE_INSTRUCTION_6502(INX);
DECLARE_INSTRUCTION_6502(INY);
DECLARE_INSTRUCTION_6502(JMP);
DECLARE_INSTRUCTION_6502(JSR);
DECLARE_INSTRUCTION_6502(LDA);
DECLARE_INSTRUCTION_6502(LDX);
DECLARE_INSTRUCTION_6502(LDY);
DECLARE_INSTRUCTION_6502(LSR);
DECLARE_INSTRUCTION_6502(NOP);
DECLARE_INSTRUCTION_6502(ORA);
DECLARE_INSTRUCTION_6502(PHA);
DECLARE_INSTRUCTION_6502(PHP);
DECLARE_INSTRUCTION_6502(PLA);
DECLARE_INSTRUCTION_6502(PLP);
DECLARE_INSTRUCTION_6502(ROL);
DECLARE_INSTRUCTION_6502(ROR);
DECLARE_INSTRUCTION_6502(RTI);
DECLARE_INSTRUCTION_6502(RTS);
DECLARE_INSTRUCTION_6502(SBC);
DECLARE_INSTRUCTION_6502(SEC);
DECLARE_INSTRUCTION_6502(SED);
DECLARE_INSTRUCTION_6502(SEI);
DECLARE_INSTRUCTION_6502(STA);
DECLARE_INSTRUCTION_6502(STX);
DECLARE_INSTRUCTION_6502(STY);
DECLARE_INSTRUCTION_6502(TAX);
DECLARE_INSTRUCTION_6502(TAY);
DECLARE_INSTRUCTION_6502(TSX);
DECLARE_INSTRUCTION_6502(TXA);
DECLARE_INSTRUCTION_6502(TXS);
DECLARE_INSTRUCTION_6502(TYA);
DECLARE_INSTRUCTION_6502(XXX);

static addressing_mode ADDRESS_MODE_TABLE[256] =
{
	ADDRESSING_IMPLIED,		ADDRESSING_INDIRECT_X,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_ACCUMULATOR,	ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_ABSOLUTE,	ADDRESSING_INDIRECT_X,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_ACCUMULATOR,	ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_IMPLIED,		ADDRESSING_INDIRECT_X,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_ACCUMULATOR,	ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_IMPLIED,		ADDRESSING_INDIRECT_X,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_ACCUMULATOR,	ADDRESSING_IMMEDIATE,		ADDRESSING_INDIRECT,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_IMPLIED,			ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_Y,	ADDRESSING_ZEROPAGE_Y,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_IMPLIED,			ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_Y,	ADDRESSING_ZEROPAGE_Y,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_Y,
	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_IMPLIED,			ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_IMMEDIATE,	ADDRESSING_INDIRECT_X,	ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_ZEROPAGE,		ADDRESSING_IMPLIED,	ADDRESSING_IMMEDIATE,		ADDRESSING_IMPLIED,			ADDRESSING_IMMEDIATE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,		ADDRESSING_ABSOLUTE,
	ADDRESSING_RELATIVE,	ADDRESSING_INDIRECT_Y,	ADDRESSING_NONE,			ADDRESSING_INDIRECT_Y,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_ZEROPAGE_X,	ADDRESSING_IMPLIED,	ADDRESSING_ABSOLUTE_Y,	ADDRESSING_IMPLIED,			ADDRESSING_ABSOLUTE_Y,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,	ADDRESSING_ABSOLUTE_X,
};

static instruction_6502* OPCODE_TABLE[256] =
{
	BRK, ORA, XXX, XXX, XXX, ORA, ASL, XXX, PHP, ORA, ASL, XXX, XXX, ORA, ASL, XXX,
	BPL, ORA, XXX, XXX, XXX, ORA, ASL, XXX, CLC, ORA, XXX, XXX, XXX, ORA, ASL, XXX,
	JSR, AND, XXX, XXX, BIT, AND, ROL, XXX, PLP, AND, ROL, XXX, BIT, AND, ROL, XXX,
	BMI, AND, XXX, XXX, XXX, AND, ROL, XXX, SEC, AND, XXX, XXX, XXX, AND, ROL, XXX,
	RTI, EOR, XXX, XXX, XXX, EOR, LSR, XXX, PHA, EOR, LSR, XXX, JMP, EOR, LSR, XXX,
	BVC, EOR, XXX, XXX, XXX, EOR, LSR, XXX, CLI, EOR, XXX, XXX, XXX, EOR, LSR, XXX,
	RTS, ADC, XXX, XXX, XXX, ADC, ROR, XXX, PLA, ADC, ROR, XXX, JMP, ADC, ROR, XXX,
	BVS, ADC, XXX, XXX, XXX, ADC, ROR, XXX, SEI, ADC, XXX, XXX, XXX, ADC, ROR, XXX,
	XXX, STA, XXX, XXX, STY, STA, STX, XXX, DEY, XXX, TXA, XXX, STY, STA, STX, XXX,
	BCC, STA, XXX, XXX, STY, STA, STX, XXX, TYA, STA, TXS, XXX, XXX, STA, XXX, XXX,
	LDY, LDA, LDX, XXX, LDY, LDA, LDX, XXX, TAY, LDA, TAX, XXX, LDY, LDA, LDX, XXX,
	BCS, LDA, XXX, XXX, LDY, LDA, LDX, XXX, CLV, LDA, TSX, XXX, LDY, LDA, LDX, XXX,
	CPY, CMP, XXX, XXX, CPY, CMP, DEC, XXX, INY, CMP, DEX, XXX, CPY, CMP, DEC, XXX,
	BNE, CMP, XXX, XXX, XXX, CMP, DEC, XXX, CLD, CMP, XXX, XXX, XXX, CMP, DEC, XXX,
	CPX, SBC, XXX, XXX, CPX, SBC, INC, XXX, INX, SBC, NOP, XXX, CPX, SBC, INC, XXX,
	BEQ, SBC, XXX, XXX, XXX, SBC, INC, XXX, SED, SBC, XXX, XXX, XXX, SBC, INC, XXX,
};
